#!/bin/bash
# Interactive TUI for adding secrets to macOS Keychain and .zshrc

set -e

# Colors
BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

ZSHRC="${HOME}/.zshrc"

echo ""
echo -e "${BOLD}🔐 macOS Keychain Secret Manager${NC}"
echo -e "${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Prompt for service name (keychain identifier)
echo -e "${BLUE}Enter a name for this secret${NC}"
echo -e "${DIM}This is the identifier used in Keychain (e.g., claude_code_oauth_token, openai_api_key)${NC}"
read -p "> " SERVICE_NAME

if [[ -z "$SERVICE_NAME" ]]; then
  echo -e "${RED}Error: Service name cannot be empty${NC}"
  exit 1
fi

# Sanitize service name (lowercase, underscores)
SERVICE_NAME=$(echo "$SERVICE_NAME" | tr '[:upper:]' '[:lower:]' | tr ' -' '_')

echo ""

# Prompt for env var name (optional)
DEFAULT_ENV_VAR=$(echo "$SERVICE_NAME" | tr '[:lower:]' '[:upper:]')
echo -e "${BLUE}Enter the environment variable name${NC}"
echo -e "${DIM}Press enter to use: ${DEFAULT_ENV_VAR}${NC}"
read -p "> " ENV_VAR_NAME

if [[ -z "$ENV_VAR_NAME" ]]; then
  ENV_VAR_NAME="$DEFAULT_ENV_VAR"
fi

# Uppercase the env var
ENV_VAR_NAME=$(echo "$ENV_VAR_NAME" | tr '[:lower:]' '[:upper:]')

echo ""

# Securely prompt for the secret value
echo -e "${BLUE}Enter the secret value${NC}"
echo -e "${DIM}(input is hidden)${NC}"
read -s -p "> " SECRET_VALUE
echo ""

if [[ -z "$SECRET_VALUE" ]]; then
  echo -e "${RED}Error: Secret value cannot be empty${NC}"
  exit 1
fi

# Confirm
echo ""
echo -e "${YELLOW}Summary:${NC}"
echo -e "  Keychain service: ${BOLD}${SERVICE_NAME}${NC}"
echo -e "  Environment var:  ${BOLD}${ENV_VAR_NAME}${NC}"
echo -e "  Secret length:    ${BOLD}${#SECRET_VALUE} characters${NC}"
echo ""
read -p "Proceed? [Y/n] " CONFIRM

if [[ "$CONFIRM" =~ ^[Nn] ]]; then
  echo -e "${YELLOW}Cancelled.${NC}"
  exit 0
fi

echo ""

# Store in Keychain
echo -e "${DIM}Storing in Keychain...${NC}"
if security add-generic-password -U -a "$USER" -s "$SERVICE_NAME" -w "$SECRET_VALUE" 2>/dev/null; then
  echo -e "${GREEN}✓${NC} Stored in Keychain"
else
  echo -e "${RED}✗${NC} Failed to store in Keychain"
  exit 1
fi

# Build the export line
EXPORT_LINE="export ${ENV_VAR_NAME}=\$(security find-generic-password -a \"\$USER\" -s \"${SERVICE_NAME}\" -w 2>/dev/null)"

# Check if already in .zshrc
if grep -qF "$SERVICE_NAME" "$ZSHRC" 2>/dev/null; then
  echo -e "${YELLOW}!${NC} Entry for '${SERVICE_NAME}' already exists in .zshrc"
  echo -e "${DIM}  You may want to update it manually${NC}"
else
  # Add to .zshrc
  echo "" >> "$ZSHRC"
  echo "# ${ENV_VAR_NAME} from Keychain (autogenerated by macos-keychain-secrets skill)" >> "$ZSHRC"
  echo "$EXPORT_LINE" >> "$ZSHRC"
  echo -e "${GREEN}✓${NC} Added to ~/.zshrc"
fi

# Source .zshrc in current shell
echo ""
echo -e "${DIM}To load in current terminal, run:${NC}"
echo -e "  ${BOLD}source ~/.zshrc${NC}"
echo ""
echo -e "${GREEN}Done!${NC} Your secret is now securely stored."
